version: "3"

services:
    backend:
        image: borwornpob/f2-cedt-backend-go
        ports:
            - "5001:5001"
        environment:
            - JUDGE0_API_URL=""
        depends_on:
            - mongo
        networks:
            - app-network

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongo-data:
        driver: local
